[server]
enableWebsocketCompression = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5000
maxMessageSize = 5000

[theme]
base = "light"
backgroundColor = "#EDFFFF"
secondaryBackgroundColor = "#CCDAFF"
